---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86151.
--- DateTime: 2023/10/24 22:24
---
--参数列表
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

--库存 / 订单 key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    --代表库存不足
    return 1
end
--判断用户是否下过单
if(redis.call('sismember', orderKey, userId) == 1) then
    --存在说明下过单
    return 2
end
--扣减库存
redis.call('incrby', stockKey, -1)
--保存用户信息
redis.call('sadd', orderKey, userId)

--判断有抢购资格后发消息到redis中的消息队列
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0